[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
optimizer_runs = 200
verbosity = 3 # display errors
match_contract = "Unit" # only runs unit tests by default
sizes = true
fs_permissions = [{ access = "read-write", path = "./"}]
# via_ir = true

[fuzz]
runs = 1000

[profile.CI] # run via FOUNDRY_PROFILE=CI foundry test
fs_permissions = [{ access = "read", path = "./node_modules/@jbx-protocol/juice-contracts-v3/deployments/mainnet"}] # Get the deployment addresses for forking
match_contract = "Unit || Fork" 

[fmt]
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config